#ifndef GLOBALMODEL_GLOBAL_H
#define GLOBALMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GLOBALMODEL_LIBRARY)
    #define GLOBALMODELSHARED_EXPORT Q_DECL_EXPORT
#else
    #define GLOBALMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GLOBALMODEL_GLOBAL_H
