#ifndef GRAPHICSMODULE_GLOBAL_H
#define GRAPHICSMODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAPHICSMODULE_LIBRARY)
    #define GRAPHICSMODULESHARED_EXPORT Q_DECL_EXPORT
#else
    #define GRAPHICSMODULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAPHICSMODULE_GLOBAL_H
